### PR TITLE
Bugfix with headers

### PR DESCRIPTION
**Pull request by Nyholm**
I messed up in #27.

Im not sure how, but headers are json-decoded somewhere. 

I tested SQS and I can know this is a fix. 

I will test the SNS now.

### CODE REVIEW

**Comment by Nyholm** [comment]
Oh.. hm.. maybe not. It depends on when serializer I use.

Hm..

**Comment by Nyholm** [comment]
What I think is happening... If the serializer dont pass any headers. We use PHP array `[]` as headers. We json_encode the headers and put it on the queue. 

When we later receive the the message. We intrepid `json_encode([]) === array()`. Which is strange..

However, if we put a message on the queue with some headers, we get a nice json string and we are not confused with json string `[]` and PHP array `[]` anymore..

**Comment by mnapoli** [comment]
Could it be that `json_encode([])` is encoded into `{}` in JSON? I've had this problem before.

Is the PR good now, or are you still looking into a fix?

**Comment by Nyholm** [comment]
5 more min. Im confirming

**Comment by mnapoli** [comment]
ha no worries 😄

**Comment by Nyholm** [comment]
So. I was confused and wrong before. 

The data that comes from SQS has Message Attributes like: 

```json
# with headers
"messageAttributes": {
        "Headers": {
            "stringValue": "{\"type\":\"Rawls\\\\DebugBundle\\\\Message\\\\Command\\\\PingAsync\",\"X-Message-Stamp-Symfony\\\\Component\\\\Messenger\\\\Stamp\\\\BusNameStamp\":\"[{\\\"busName\\\":\\\"messenger.bus.command\\\"}]\",\"Content-Type\":\"application\\/json\"}",
            "stringListValues": [],
            "binaryListValues": [],
            "dataType": "String"
        }
    },
```

```json
# without headers
 "messageAttributes": {
        "Headers": {
            "stringValue": "[]",
            "stringListValues": [],
            "binaryListValues": [],
            "dataType": "String"
        }
    },
```

I was not aware of the `stringValue` key. That is why I saw an array. 

This PR is ready to be merged.

**Pull request merged**
