### PR TITLE
Allow Symfony 6.0

### PR DESCRIPTION
**Pull request by ddeboer**

### CODE REVIEW

**Comment by ddeboer** [comment]
For the test error, see https://github.com/SymfonyTest/symfony-bundle-test/issues/65.

**Comment by mnapoli** [comment]
Thanks! It seems like we need to wait for https://github.com/SymfonyTest/symfony-bundle-test/issues/65 before merging then

**Comment by ddeboer** [comment]
`symfony-bundle-test` being a dev dependency, I decided to require `1.x-dev` so we can move forward with Symfony 6 support.

**Comment by mnapoli** [comment]
Sounds good to me, thank you!

**Pull request merged**
