### PR TITLE
Add support for EventBusName with EventBridgeTransport

### LINKED ISSUE #51: Sending message to a custom event bus
Looking through `EventBridgeTransport.php` it appears it does not allow you to send events to a custom event bus.            
    [
                     'Detail' => json_encode($encodedMessage, JSON_THROW_ON_ERROR),
                    // Ideally here we could put the class name of the message, but how to retrieve it?
                    'DetailType' => 'Symfony Messenger message',
                    'Source' => $this->source,
                ]

Is this the case...or am I missing something.

### PR DESCRIPTION
**Pull request by starred-gijs**
Fixes #51

Adds support for EventBridgeName with EventBridgeTransport

### CODE REVIEW

**Comment by mnapoli** [comment]
Thank you!

**Comment by mnapoli** [comment]
Oh I just realized after merging that it wasn't documented, would you be able to send a PR to mention that new feature in the documentation?

**Comment by starred-gijs** [comment]
Sure will do that, what is the target release version? I will update the Changelog as well

**Comment by mnapoli** [comment]
It will be 0.4.2

**Pull request merged**
