### PR TITLE
Implement receiver methods for SQS.

### PR DESCRIPTION
**Pull request by starred-gijs**
Allow consuming SQS messages via the worker (`messenger:consume`) , to ease local development.

### CODE REVIEW

**Comment by mnapoli** [comment]
Thanks for the PR!

As I told you on Slack, I don't see that much value in the feature but I understand that it can be useful, and given that the PR is really simple, why not!

@Nyholm wdyt?

However (and this is the not-fun part), if we implement that in SQS, we should also probably implement that in EventBridge and SNS as well?

**Comment by Nyholm** [comment]
Hm. I like this idea. But this is provided by Symfony 5.1. This PR basically is a small duplication of the Symfony package. 

This PR also makes this library a tight coupling to the official AWS SDK which is something I would like us to remove. 

So given that @mnapoli see little value in the PR and my two reasons above. I would like to close this PR. I do think you did a great job implementing this, but it will be redundant next month when SF 5.1 is released.

**Comment by starred-gijs** [comment]
Thanks for your replies! Im fine with closing this PR, for now I can maintain my fork. 

Is the plan to make this package compatible with symfony/amazon-sqs-messenger when its released?

(I noticed a difference with how the body/headers are stored, so keep that in mind)

**Comment by Nyholm** [comment]
Is the plan to make this package compatible with symfony/amazon-sqs-messenger when its released?

Yes. You should be able to use this library to post a message and consume it with `symfony/amazon-sqs-messenger`. 
Im not sure if one should be able to use `symfony/amazon-sqs-messenger` for posting. 

> (I noticed a difference with how the body/headers are stored, so keep that in mind)

Oh, I haven't looked into this too much. Thank you. 

Could you open an issue so we dont forget this?

**Comment by starred-gijs** [comment]
Lol that was changed yesterday, see https://github.com/symfony/amazon-sqs-messenger/commit/fdfbdcc58c80b34490314f98fe26b9702d1d00ab

**Comment by Nyholm** [comment]
Ah, okey. That is why Jeremey created https://github.com/async-aws/testing-sqs

=)

**Pull request closed without merging**
