### PR TITLE
Replace Sqs implementation with symfony/amazon-sqs-messenger.

### LINKED ISSUE #29: Use symfony/amazon-sqs-messenger Transport for sending messages
I was wondering if it is an idea now symfony/amazon-sqs-messenger is released, to use the Transport from that package so this package handles only the serverless consumer side?
Does that make sense?

I doesn't seem right to keep that functionality in 2 places?

### PR DESCRIPTION
**Pull request by starred-gijs**
Fixes #29 

Some observations:
- the dsn must start with `sqs://`
- If using the Symfony Serializer, you need [this fix](https://github.com/symfony/amazon-sqs-messenger/commit/ddb0226c680d15ac9d4eb158efc8a9ba718d7d12) (scheduled for symfony/amazon-sqs-messenger next release) see #31

### CODE REVIEW

**Comment by mnapoli** [comment]
Thanks!

The only thing that bothers me is that we have to prefix SQS URLs with `sqs://`. That prevents from using CloudFormation in serverless.yml to put the queue URL in an environment variable.

Do you think there is any way to support `https://` URLs?

**Comment by starred-gijs** [comment]
Let me do some checks, maybe we need to create a PR in the symfony/amazon-sqs-messenger package to accomplish this. 

For my local development, I have a container running on https://sqs:9324 so for that reason I needed to tweak the SqsTransportFactory. Hopefully we can address both use cases in 1 solution.

**Comment by starred-gijs** [comment]
I created a PR, lets see what the feedback is.
 https://github.com/symfony/symfony/pull/37306

**Comment by starred-gijs** [comment]
Closed in favor of #31

**Pull request closed without merging**
