### PR TITLE
Dispatch worker event to be compatible with symfony messenger

### PR DESCRIPTION
**Pull request by TNAJanssen**
Hi,

I added dispatching the worker message events so that it will be more compatible with Symfony Messenger.

### CODE REVIEW

**Comment by mnapoli** [comment]
Thank you, I am afraid that these events might interfere with the behavior we want on Lambda (e.g. not catch exceptions, leave retries to SQS, etc.). Do you know if that's the case by default with Symfony? (e.g. have you tested this?)

Also, do you have a use case in mind for merging this?

**Comment by Nyholm** [comment]
Thank you for this PR. 

I like this idea. This is actually why we introduced the "BusDriver" abstraction. That allows us to create integrations like this: https://github.com/Happyr/bref-messenger-failure-strategies

This `BusDriver` is doing the exact same thing as this PR. 

Could we: 
A) Show a link to https://github.com/Happyr/bref-messenger-failure-strategies in the  docs so it is found?
B) Include this abstraction as an "alternative bus driver" in this library?

**Comment by mnapoli** [comment]
Regarding this PR, I still don't understand it. An actual use case may help.

Regarding https://github.com/Happyr/bref-messenger-failure-strategies, I understand that some people will prefer using the tools they are used to.

However, the goal with Bref and this package is to adapt Messenger to the practices related to Lambda. That is why the goal is to use Lambda's retry mechanisms. I think https://github.com/Happyr/bref-messenger-failure-strategies should stay a separate package, and not be offered as a choice to users because this is the opposite of where this package is driving them.

**Comment by Nyholm** [comment]
So. To help people like me and @TNAJanssen, could we add a link to  https://github.com/Happyr/bref-messenger-failure-strategies in the docs?

**Comment by mnapoli** [comment]
Just to be clear, in my opinion that wouldn't make sense to simply link to the package in the docs. That would be like writing this:

> This is how you should use Symfony Messenger with Lambda/Bref. By the way, look [here](#) to do the opposite of what we describe.

However, we could approach this from a use-case perspective.

If we can find a use case where that would make sense, then why not, i.e. this alternative would work:

> This is how you should use Symfony Messenger with Lambda/Bref in most cases. However, in case you specifically want to do X or Y, look [here](#) for a more appropriate approach.

**Comment by mnapoli** [comment]
(and I am back to my point where I don't understand *why* this PR, what is the use case behind it, which is why we can't merge it as such)

**Comment by Nyholm** [comment]
Okey. 

This PR allows you to use Symfony's "retry strategies" for messenger. 

I don't thing we should merge this PR. This library has an abstraction so it can allow this feature. That is what I implemented in the Happyr package. 

What I do suggest is to add something like the following in the docs for this library: 

> This is how you should use Symfony Messenger with Lambda/Bref in most cases. However, in case you want to use Symfony's retry strategies over AWS dead letter queues, have a look at [this package](#) for how to use that feature.

**Comment by mnapoli** [comment]
> I don't thing we should merge this PR. This library has an abstraction so it can allow this feature. That is what I implemented in the Happyr package.

👍 

> "However, in case you want to use Symfony's retry strategies over AWS dead letter queues"

That is not a use case, that is a solution. Readers will not know _when_ they need this, which is why I don't want to offer any choice (unless we guide them through said choice).

**Comment by mnapoli** [comment]
I pushed documentation in #26 to avoid surprises like these and explain that this package integrates with Lambda's retry mechanism instead.

**Pull request closed without merging**
