### PR TITLE
Support Symfony 7.0

### PR DESCRIPTION
**Pull request by smoench**
This PR aligns with https://github.com/brefphp/symfony-bridge/pull/67.
It bumps minimum Symfony version to 5.4 and minimum PHP version to 8.0.

Blocked by:
- [x] https://github.com/SymfonyTest/symfony-bundle-test/pull/83
- [x] https://github.com/SymfonyTest/symfony-bundle-test/pull/78

### CODE REVIEW

**Comment by mnapoli** [comment]
👍 feel free to ping me when the CI is green (I don't get notifications when new commits are pushed)

**Comment by verschoof** [comment]
Hi @smoench I think both references you gave are solved.

**Comment by smoench** [comment]
@verschoof Sure, but no [new version has been released](https://github.com/SymfonyTest/symfony-bundle-test/releases) yet

**Comment by smoench** [comment]
Hey @mnapoli, a new version from symfony-bundle-test has been released and CI is green :-)

**Comment by mnapoli** [comment]
Thank you!

**Pull request merged**
