### PR TITLE
Simple KafkaConsumer

### PR DESCRIPTION
**Pull request by rejinka**
As a follow-up to https://github.com/brefphp/bref/pull/1216, i implemented a simple consumer for kafka events.

### CODE REVIEW

**Comment by t-richard** [comment]
Hi, 

Thanks for the PR :+1: 

I see you added a consumer but no transport and I don't think Symfony messenger has one built-in.

This is what we do for SNS and EventBridge for example: https://github.com/brefphp/symfony-messenger/blob/master/src/Service/Sns/SnsTransport.php

**Comment by rejinka** [comment]
I assume implementing a transport wouldn't be possible without adding a dependency on rdkafka, as aws hasn't any abstraction-layer. Anyway, my idea was to implement a consumer for kafka, like it was done for sqs (and therefore a similiar usage): https://github.com/brefphp/symfony-messenger/tree/7a687c303565cdc06c9efe01e8af526c1990e498#sqs

**Comment by t-richard** [comment]
> my idea was to implement a consumer for kafka, like it was done for sqs

SQS used to have a transport here, it was just replaced with the official one from Symfony when it came out.

How are you sending Messenger messages to Kafka at the moment ?

**Comment by rejinka** [comment]
In other services, we produce messages with https://github.com/KonstantinCodes/messenger-kafka, which hopefully at some point gets integrated into symfony: https://github.com/symfony/symfony/pull/39712. In this service, we just consume and probably will never produce anything.

**Comment by t-richard** [comment]
There's also this package that bridges enqueue and messenger : https://github.com/sroze/messenger-enqueue-transport

And enqueue has support for Kafka apparently.

We coud advise to use one of those. That would also reduce maintenance needed in this repo.

Any thoughts @mnapoli?

**Comment by t-richard** [comment]
> I agree with @t-richard here. It will be easier for maintenance to keep this package focused on some services, and leave Kafka support as a separate 3rd party package

My suggestion was to introduce the consumer as is but suggest to use a third party transport to send messages to Kafka. Because we have the Kafka typed handler now, it seems legit to have a consumer in the bridge

**Comment by mnapoli** [comment]
Ah ok I see.

It doesn't look like a great experience for users, they'd have to juggle with different packages. I'd rather not promise support for Kafka unless we can cover it correctly honestly. I see no reason for Kafka support to exist in this package instead of another one dedicated to support Kafka.

**Pull request closed without merging**
