### PR TITLE
Use AsyncAws instead of the official SDK

### PR DESCRIPTION
**Pull request by Nyholm**
This is including commits from #16.

### CODE REVIEW

**Comment by mnapoli** [comment]
I had a look at the last commit (which is the one for the PR), it introduces a lot of complexity for gains I do not see.

Why this PR?

**Comment by Nyholm** [comment]
Thank you for the review. 

I need this because I want to be able to use `bref/symfony-messenger` without using the official SDK.

**Comment by Nyholm** [comment]
Make sure you checkout and review the PR. The last commit is basically just duplicating the transports and transport factories.

**Comment by mnapoli** [comment]
> Make sure you checkout and review the PR. The last commit is basically just duplicating the transports and transport factories.

Yes this is what I reviewed.

> I need this because I want to be able to use bref/symfony-messenger without using the official SDK.

Got you, why do you want to do that?

Is this to optimize the size on Lambda? If that's the case, then what about switching to that package entirely instead?

**Comment by mnapoli** [comment]
Maybe we should have a look at this + https://github.com/brefphp/symfony-messenger/pull/16/files#r395140878 another way, here is an idea:

what about considering the AWS clients as internal details. I.e. we do not let users pass their own implementation, or be able to override them.

After all, what do they need to override? The credentials are provided by Lambda, the region as well, and the "API version" is something we should control.

WDYT?

**Comment by mnapoli** [comment]
> what about considering the AWS clients as internal details. I.e. we do not let users pass their own implementation, or be able to override them.

Tried that but it quickly got ugly.

I worked on some kind of middleground with this idea in #22, which could replace #16, and then we could migrate entirely to Async AWS so that the dependency is lighter for users.

Let me know what you think.

**Comment by Nyholm** [comment]
> > what about considering the AWS clients as internal details. I.e. we do not let users pass their own implementation, or be able to override them.

> Tried that but it quickly got ugly.

Yes, I know. I started there too =)

> Let me know what you think.

I left you a comment at https://github.com/brefphp/symfony-messenger/pull/22#issuecomment-626295506

------

I've update the PR, This removes some complexity and AWS.

**Comment by Nyholm** [comment]
Parts of this was merged into master. I'll keep this branch around but I'll close the PR. 

Thank you for the reviews.

**Pull request closed without merging**
