### PR TITLE
Feature(sqs): Add xray trace id to enveloppe stamps

### PR DESCRIPTION
**Pull request by hadeli**
In order to trace messages with the xray service, i need to fetch trace id from context and propagate it with a messenger stamp.

### CODE REVIEW

**Review by mnapoli — APPROVED** [review]
Awesome thank you, let's wait for the tests to pass and I'll merge.

**Comment by mnapoli** [comment]
Oh no, this is the yearly "the build fails for an unrelated reason because some dependency changed something somewhere" 😢

**Comment by mnapoli** [comment]
I pushed https://github.com/brefphp/symfony-messenger/commit/91e2abbb38341ff8ac7036e7c53ce454ef4ef1e5 in the hopes it fixes the build on master. Then you should be able to rebase on master (or merge master in your branch).

**Comment by shouze** [comment]
@hadeli I guess that we also need to add a class exists assertion for php 7.3 because this class didn't exists in previous Messenger releases.
```

1) Bref\Symfony\Messenger\Test\Unit\Service\Sqs\SqsConsumerTest::testSerializerWithXRayHeader
Error: Class 'Symfony\Component\Messenger\Bridge\AmazonSqs\Transport\AmazonSqsXrayTraceHeaderStamp' not found
```

@mnapoli another option is to remove support of php 7.3 as it's not maintained anymore, WDYT?
[image
](https://www.php.net/supported-versions.php)

**Comment by mnapoli** [comment]
100% 👍  to remove support for PHP 7.3

**Comment by shouze** [comment]
> 100% 👍  to remove support for PHP 7.3

@mnapoli looks like it's ✅

**Review by mnapoli — APPROVED** [review]

**Comment by mnapoli** [comment]
Thank you!

**Pull request merged**
